#' Assess an R Package riskmetric with package name and version
#'
#' This function use `risk.assessr::assess_pkg` assessment function with only the package name and version
#'
#' @param package_name A character string specifying the name of the package to assess.
#' @param version A character string specifying the version of the package to assess. Default is `NA`, which assesses the latest version.
#' @param repos A character string specifying the repo directly. Default is getOption("repos")
#'
#' @return The function returns a list of assessment results generated by the `risk.assessr::assess_pkg` function. 
#' If the package cannot be downloaded or installed, an error message is returned.
#'
#' @details This function follows these steps:
#' \enumerate{
#'   \item Downloads the specified R package
#'   \item Installs the downloaded package in a temporary location.
#'   \item Runs the `risk.assessr::assess_pkg` function to assess the package for risks and issues.
#'   \item Returns the results of the assessment.
#' }
#'
#' @examples
#' \dontrun{
#' assess_pkg_r_package(
#'   "here", version = "1.0.1", repos =  "http://cran.us.r-project.org"
#' )
#' }
#' @importFrom remotes download_version
#' @export
assess_pkg_r_package <- function(package_name, version=NA, repos = getOption("repos")) {
  
  temp_file <- get_package_tarfile(package_name = package_name, version = version, repos = repos)
  
  if (is.null(temp_file)) {
    return(NULL)
  }
  
  # If no error, proceed with the package tarball
  modified_tar_file <- modify_description_file(temp_file)
  
  # Set up the package using the temporary file
  install_list <- set_up_pkg(modified_tar_file)
  
  # Extract information from the installation list
  build_vignettes <- install_list$build_vignettes
  package_installed <- install_list$package_installed
  pkg_source_path <- install_list$pkg_source_path
  rcmdcheck_args <- install_list$rcmdcheck_args
  
  # Check if the package needs to be installed locally
  package_installed <- install_package_local(pkg_source_path)
  
  # Check if the package was installed successfully
  if (package_installed == TRUE) {
    rcmdcheck_args$path <- pkg_source_path
    
    # Pass custom risk config if provided
    assess_package <- assess_pkg(
      pkg_source_path = pkg_source_path,
      rcmdcheck_args = rcmdcheck_args
    )
  } else {
    message("Package installation failed.")
    assess_package <- NULL
  }
  
  # Clean up: remove the temporary file
  unlink(temp_file)
  
  return(assess_package)
}